layout_spectrum: 0.6916338
color:
  saturation: 0.9251767
  lightness: 0.4916558
  brandStrength: 0.3662766
  brandColors:
    - '#C5CED8'
    - '#272830'
    - '#FFFFFF'
    - '#8F9CAB'
    - '#654C41'
  rhythmicContrast: 0.2169606
typography_spectrum: 0.5595676
name: Jasonj
